name: Test & Publish Code Coverage
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
        with:
          python-version: 3.8
    - name: Pylint
      run: pylint solvers --fail-under=10
    # - name: Test & Publish code coverage
    #   uses: paambaati/codeclimate-action@v3.2.0
    #   with:
    #     coverageCommand: dotnet test --collect:"XPlat Code Coverage" --settings coverlet.runsettings
    #     coverageLocations: ${{ github.workspace }}/AdventOfCode15.Tests/TestResults/**/*.xml:cobertura
    #     prefix: /${{ github.workspace }}
    #   env:
    #     CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}